In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./datas/employees.csv')
df.describe()

       employee_id        salary  commission_pct  manager_id  department_id
count   107.000000    107.000000       35.000000  106.000000     106.000000
mean    153.000000   6461.682243        0.222857  124.764151      63.207547
std      31.032241   3909.365746        0.085184   20.315395      20.910110
min     100.000000   2100.000000        0.100000  100.000000      10.000000
25%     126.500000   3100.000000        0.150000  108.000000      50.000000
50%     153.000000   6200.000000        0.200000  122.000000      50.000000
75%     179.500000   8900.000000        0.300000  145.000000      80.000000
max     206.000000  24000.000000        0.400000  205.000000     110.000000

In [4]:
df.head(5)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0

In [5]:
df.isna().sum()

employee_id        0
first_name         0
last_name          0
email              0
phone_number       0
job_id             0
salary             0
commission_pct    72
manager_id         1
department_id      1
dtype: int64

In [6]:
df.nsmallest(1,"salary")  #tips:找出薪资最低的员工

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [7]:
df.nlargest(1,'salary') #tips:找出薪资最高的

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0

In [8]:
df[df['salary']==df['salary'].min()] #tips:利用布尔索引找出薪资最低的员工

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [11]:
df.sort_values(by='salary',ascending=False).tail(1) #tips:用排序法找到薪资最低的

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [12]:
df.nlargest(10,'salary') #tips:找出薪资最高的前十名员工

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,SA_MAN,14000.0,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,SA_MAN,13500.0,0.30,100.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,MK_MAN,13000.0,NaN,100.0,20.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,SA_MAN,12000.0,0.30,100.0,80.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,SA_REP,11500.0,0.25,148.0,80.0

In [13]:
df.columns

Index(['employee_id', 'first_name', 'last_name', 'email', 'phone_number',
       'job_id', 'salary', 'commission_pct', 'manager_id', 'department_id'],
      dtype='str')

In [14]:
df['department_id'].unique() #tips:查询所有部门的id

array([ 90.,  60., 100.,  30.,  50.,  80.,  nan,  10.,  20.,  40.,  70.,
       110.])

In [3]:
#查询每个部门员工的人数
df.groupby('department_id')['employee_id'].sum()

department_id
10.0      200
20.0      403
30.0      699
40.0      203
50.0     7090
60.0      525
70.0      204
80.0     5492
90.0      303
100.0     663
110.0     411
Name: employee_id, dtype: int64

In [6]:
df.groupby('department_id')['salary'].mean()

department_id
10.0      4400.000000
20.0      9500.000000
30.0      4150.000000
40.0      6500.000000
50.0      3475.555556
60.0      5760.000000
70.0     10000.000000
80.0      8955.882353
90.0     19333.333333
100.0     8600.000000
110.0    10150.000000
Name: salary, dtype: float64

In [4]:
#找出平均薪资最高的部门id
df.groupby('department_id')['salary'].mean().nlargest(1)

department_id
90.0    19333.333333
Name: salary, dtype: float64