In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./datas/fine_food_reviews_1k.csv')

In [3]:
df.describe()

        Unnamed: 0          Time        Score
count  1000.000000  1.000000e+03  1000.000000
mean    499.500000  1.351172e+09     4.217000
std     288.819436  4.286608e+04     1.288243
min       0.000000  1.351123e+09     1.000000
25%     249.750000  1.351123e+09     4.000000
50%     499.500000  1.351210e+09     5.000000
75%     749.250000  1.351210e+09     5.000000
max     999.000000  1.351210e+09     5.000000

In [4]:
df.shape

(1000, 7)

In [6]:
df.isna().sum()

Unnamed: 0    0
Time          0
ProductId     0
UserId        0
Score         0
Summary       0
Text          0
dtype: int64

In [7]:
df.columns

Index(['Unnamed: 0', 'Time', 'ProductId', 'UserId', 'Score', 'Summary',
       'Text'],
      dtype='object')

In [11]:
df.columns

Index(['Unnamed: 0', 'Time', 'ProductId', 'UserId', 'Score', 'Summary',
       'Text'],
      dtype='object')

In [14]:
df.columns.tolist()

['Unnamed: 0', 'Time', 'ProductId', 'UserId', 'Score', 'Summary', 'Text']

In [15]:
df.columns.tolist()[1:]

['Time', 'ProductId', 'UserId', 'Score', 'Summary', 'Text']

In [19]:
df2 = df[df.columns.tolist()[1:]]

In [20]:
df2

,Time,ProductId,UserId,Score,Summary,Text
0,1351123200,B003XPF9BO,A3R7JR3FMEBXQB,5,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...
1,1351123200,B003JK537S,A3JBPC3WFUT5ZP,1,Arrived in pieces,"Not pleased at all. When I opened the box, mos..."
2,1351123200,B000JMBE7M,AQX1N6A51QOKG,4,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...
3,1351123200,B004AHGBX4,A2UY46X0OSNVUQ,3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...
4,1351123200,B001BORBHO,A1AFOYZ9HSM2CZ,5,Happy with the product,My dog was suffering with itchy skin. He had ...
...,...,...,...,...,...,...
995,1351209600,B004OQLIHK,AKHQMSUORSA91,5,Delicious!,I have ordered these raisins multiple times. ...
996,1351209600,B0006349W6,A21BT40VZCCYT4,5,Good Training Treat,My dog will come in from outside when I am tra...
997,1351209600,B00611F084,A6D4ND3C3BCYV,5,Jamica Me Crazy Coffee,Wolfgang Puck's Jamaica Me Crazy is that wonde...
998,1351209600,B005QKH5HA,A3LR9HCV3D96I3,5,Party Peanuts,Great product for the price. Mix with the Asia...
999,1351209600,B001EQ5GEO,A3VYU0VO6DYV6I,5,I love Maui Coffee!,My first experience with Maui Coffee was bring...

In [24]:
df.columns.isna().sum()

np.int64(0)

In [23]:
df.index.isna().sum()

np.int64(0)